# Generated by Django 2.2 on 2019-10-01 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actorid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('photo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=4)),
                ('length', models.CharField(max_length=10)),
                ('genres', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('poster', models.URLField(default='')),
                ('plot', models.CharField(max_length=500)),
                ('trailer', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('movieid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('movieid', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Expect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('movieid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actorid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.Actor')),
                ('movieid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
    ]
