# Generated by Django 2.2 on 2019-10-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20191004_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('fram', models.TextField()),
                ('movieid', models.ForeignKey(on_delete=True, to='movie.Movie')),
            ],
        ),
    ]
