# Generated by Django 2.2 on 2019-10-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_fram'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fram',
            new_name='Frame',
        ),
        migrations.RenameField(
            model_name='frame',
            old_name='fram',
            new_name='frame',
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=55),
        ),
    ]
