# Generated by Django 2.2 on 2019-10-04 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0004_auto_20191004_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('movieid', models.ForeignKey(on_delete=True, to='movie.Movie')),
                ('user', models.ForeignKey(blank=True, on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
