# Generated by Django 2.2 on 2019-10-06 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_remove_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datestamp',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
