# Generated by Django 2.2 on 2019-10-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_comment_datestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='requested',
            field=models.IntegerField(default=0),
        ),
    ]
