# Generated by Django 2.2 on 2019-10-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_movie_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='datestamp',
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
